### ISSUE TITLE
Rename 2d to 3d in hardware types

### ISSUE THREAD

**Issue by anujdeshpande** [product-os/rfq#8]
@rcooke-warwick do you remember why we had done that in the first place?
I am about to enable this for a case for balenaFin, and wanted didn't want to have type 2d in that spec

**Comment by rcooke-warwick** [comment]
@anujdeshpande I think we originally did this because we thought there might be a distinction between something like the case, which is a hollow 3d structure and a 2d flat piece like the heatsink - the 2d piece can be lasercut, 3d piece could be injection moulded. We could just scrap this distinction now I guess, and let the manufacturing lab differentiate between the two

**Comment by anujdeshpande** [comment]
Sounds good - I'll open a PR here. And one on the heatsink repo as well
